// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ5SKjbWa8Ls0-87n6Jz67JEpH0rf6FB0',
    appId: '1:905851321647:web:39c2ecc1f23557467d75da',
    messagingSenderId: '905851321647',
    projectId: 'sonia-ai-8141d',
    authDomain: 'sonia-ai-8141d.firebaseapp.com',
    storageBucket: 'sonia-ai-8141d.firebasestorage.app',
    measurementId: 'G-MGBV1JVX49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAEDBQm8rMrhgQvK64i-ToVjaLPFvA74',
    appId: '1:905851321647:android:f2a06fc754f9e4907d75da',
    messagingSenderId: '905851321647',
    projectId: 'sonia-ai-8141d',
    storageBucket: 'sonia-ai-8141d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC76r9Tb2621ic0nIONjZpGYtGdEqpspVg',
    appId: '1:905851321647:ios:52acead63fcbddab7d75da',
    messagingSenderId: '905851321647',
    projectId: 'sonia-ai-8141d',
    storageBucket: 'sonia-ai-8141d.firebasestorage.app',
    iosBundleId: 'com.sonialabs.sonaxia',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC76r9Tb2621ic0nIONjZpGYtGdEqpspVg',
    appId: '1:905851321647:ios:013c52a13bb6e2227d75da',
    messagingSenderId: '905851321647',
    projectId: 'sonia-ai-8141d',
    storageBucket: 'sonia-ai-8141d.firebasestorage.app',
    iosBundleId: 'com.example.examsparkFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ5SKjbWa8Ls0-87n6Jz67JEpH0rf6FB0',
    appId: '1:905851321647:web:39c2ecc1f23557467d75da',
    messagingSenderId: '905851321647',
    projectId: 'sonia-ai-8141d',
    authDomain: 'sonia-ai-8141d.firebaseapp.com',
    storageBucket: 'sonia-ai-8141d.firebasestorage.app',
    measurementId: 'G-MGBV1JVX49',
  );
}
